# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setEnabled(True)
        SettingsDialog.resize(700, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_AskSaveOnClose = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_AskSaveOnClose.setEnabled(True)
        self.checkBox_AskSaveOnClose.setChecked(True)
        self.checkBox_AskSaveOnClose.setObjectName("checkBox_AskSaveOnClose")
        self.gridLayout_4.addWidget(self.checkBox_AskSaveOnClose, 2, 0, 1, 1)
        self.checkBox_RecentFiles = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_RecentFiles.setChecked(True)
        self.checkBox_RecentFiles.setObjectName("checkBox_RecentFiles")
        self.gridLayout_4.addWidget(self.checkBox_RecentFiles, 1, 0, 1, 1)
        self.checkBox_SplashScreen = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_SplashScreen.setEnabled(True)
        self.checkBox_SplashScreen.setChecked(True)
        self.checkBox_SplashScreen.setObjectName("checkBox_SplashScreen")
        self.gridLayout_4.addWidget(self.checkBox_SplashScreen, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Distclean = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Distclean.setEnabled(True)
        self.checkBox_Distclean.setObjectName("checkBox_Distclean")
        self.gridLayout_3.addWidget(self.checkBox_Distclean, 1, 0, 1, 1)
        self.checkBox_Terminal = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Terminal.setEnabled(True)
        self.checkBox_Terminal.setObjectName("checkBox_Terminal")
        self.gridLayout_3.addWidget(self.checkBox_Terminal, 9, 0, 1, 1)
        self.lineEdit_Clean = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Clean.setEnabled(False)
        self.lineEdit_Clean.setObjectName("lineEdit_Clean")
        self.gridLayout_3.addWidget(self.lineEdit_Clean, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 10, 1, 1, 1)
        self.lineEdit_Deploy = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Deploy.setEnabled(False)
        self.lineEdit_Deploy.setObjectName("lineEdit_Deploy")
        self.gridLayout_3.addWidget(self.lineEdit_Deploy, 4, 1, 1, 1)
        self.checkBox_Run = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Run.setEnabled(True)
        self.checkBox_Run.setObjectName("checkBox_Run")
        self.gridLayout_3.addWidget(self.checkBox_Run, 5, 0, 1, 1)
        self.lineEdit_Run = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Run.setEnabled(False)
        self.lineEdit_Run.setObjectName("lineEdit_Run")
        self.gridLayout_3.addWidget(self.lineEdit_Run, 5, 1, 1, 1)
        self.lineEdit_Serve = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Serve.setEnabled(False)
        self.lineEdit_Serve.setObjectName("lineEdit_Serve")
        self.gridLayout_3.addWidget(self.lineEdit_Serve, 6, 1, 1, 1)
        self.checkBox_Deploy = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Deploy.setEnabled(True)
        self.checkBox_Deploy.setObjectName("checkBox_Deploy")
        self.gridLayout_3.addWidget(self.checkBox_Deploy, 4, 0, 1, 1)
        self.checkBox_Serve = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Serve.setEnabled(True)
        self.checkBox_Serve.setObjectName("checkBox_Serve")
        self.gridLayout_3.addWidget(self.checkBox_Serve, 6, 0, 1, 1)
        self.checkBox_Build = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Build.setEnabled(True)
        self.checkBox_Build.setObjectName("checkBox_Build")
        self.gridLayout_3.addWidget(self.checkBox_Build, 3, 0, 1, 1)
        self.lineEdit_Distclean = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Distclean.setEnabled(False)
        self.lineEdit_Distclean.setObjectName("lineEdit_Distclean")
        self.gridLayout_3.addWidget(self.lineEdit_Distclean, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 1, 1, 1)
        self.lineEdit_Terminal = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Terminal.setEnabled(False)
        self.lineEdit_Terminal.setObjectName("lineEdit_Terminal")
        self.gridLayout_3.addWidget(self.lineEdit_Terminal, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 7, 1, 1, 1)
        self.checkBox_Clean = QtWidgets.QCheckBox(self.tab)
        self.checkBox_Clean.setEnabled(True)
        self.checkBox_Clean.setObjectName("checkBox_Clean")
        self.gridLayout_3.addWidget(self.checkBox_Clean, 2, 0, 1, 1)
        self.lineEdit_Build = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Build.setEnabled(False)
        self.lineEdit_Build.setObjectName("lineEdit_Build")
        self.gridLayout_3.addWidget(self.lineEdit_Build, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.default_Clean = QtWidgets.QPushButton(self.tab)
        self.default_Clean.setObjectName("default_Clean")
        self.gridLayout_3.addWidget(self.default_Clean, 2, 2, 1, 1)
        self.default_Build = QtWidgets.QPushButton(self.tab)
        self.default_Build.setObjectName("default_Build")
        self.gridLayout_3.addWidget(self.default_Build, 3, 2, 1, 1)
        self.default_Deploy = QtWidgets.QPushButton(self.tab)
        self.default_Deploy.setObjectName("default_Deploy")
        self.gridLayout_3.addWidget(self.default_Deploy, 4, 2, 1, 1)
        self.default_Run = QtWidgets.QPushButton(self.tab)
        self.default_Run.setObjectName("default_Run")
        self.gridLayout_3.addWidget(self.default_Run, 5, 2, 1, 1)
        self.default_Serve = QtWidgets.QPushButton(self.tab)
        self.default_Serve.setObjectName("default_Serve")
        self.gridLayout_3.addWidget(self.default_Serve, 6, 2, 1, 1)
        self.default_Terminal = QtWidgets.QPushButton(self.tab)
        self.default_Terminal.setObjectName("default_Terminal")
        self.gridLayout_3.addWidget(self.default_Terminal, 9, 2, 1, 1)
        self.default_Distclean = QtWidgets.QPushButton(self.tab)
        self.default_Distclean.setObjectName("default_Distclean")
        self.gridLayout_3.addWidget(self.default_Distclean, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_CustomTarget = QtWidgets.QPlainTextEdit(self.tab_2)
        self.textEdit_CustomTarget.setObjectName("textEdit_CustomTarget")
        self.gridLayout_2.addWidget(self.textEdit_CustomTarget, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabBlacklist = QtWidgets.QWidget()
        self.tabBlacklist.setObjectName("tabBlacklist")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabBlacklist)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_BlacklistApp = QtWidgets.QCheckBox(self.tabBlacklist)
        self.checkBox_BlacklistApp.setObjectName("checkBox_BlacklistApp")
        self.gridLayout_5.addWidget(self.checkBox_BlacklistApp, 1, 0, 1, 1)
        self.checkBox_BlacklistBuildozer = QtWidgets.QCheckBox(self.tabBlacklist)
        self.checkBox_BlacklistBuildozer.setObjectName("checkBox_BlacklistBuildozer")
        self.gridLayout_5.addWidget(self.checkBox_BlacklistBuildozer, 4, 0, 1, 1)
        self.textEdit_BlacklistApp = QtWidgets.QPlainTextEdit(self.tabBlacklist)
        self.textEdit_BlacklistApp.setEnabled(False)
        self.textEdit_BlacklistApp.setObjectName("textEdit_BlacklistApp")
        self.gridLayout_5.addWidget(self.textEdit_BlacklistApp, 3, 0, 1, 1)
        self.textEdit_BlacklistBuildozer = QtWidgets.QPlainTextEdit(self.tabBlacklist)
        self.textEdit_BlacklistBuildozer.setEnabled(False)
        self.textEdit_BlacklistBuildozer.setObjectName("textEdit_BlacklistBuildozer")
        self.gridLayout_5.addWidget(self.textEdit_BlacklistBuildozer, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabBlacklist)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabBlacklist)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tabBlacklist)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabBlacklist, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_SubBuildozer = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_SubBuildozer.setObjectName("checkBox_SubBuildozer")
        self.gridLayout_7.addWidget(self.checkBox_SubBuildozer, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 1, 1, 1)
        self.textEdit_SubApp = QtWidgets.QPlainTextEdit(self.tab_4)
        self.textEdit_SubApp.setEnabled(False)
        self.textEdit_SubApp.setObjectName("textEdit_SubApp")
        self.gridLayout_6.addWidget(self.textEdit_SubApp, 2, 1, 1, 1)
        self.checkBox_SubApp = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_SubApp.setObjectName("checkBox_SubApp")
        self.gridLayout_6.addWidget(self.checkBox_SubApp, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.textEdit_SubBuildozer = QtWidgets.QPlainTextEdit(self.tab_4)
        self.textEdit_SubBuildozer.setEnabled(False)
        self.textEdit_SubBuildozer.setObjectName("textEdit_SubBuildozer")
        self.gridLayout_7.addWidget(self.textEdit_SubBuildozer, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tabTemplate = QtWidgets.QWidget()
        self.tabTemplate.setObjectName("tabTemplate")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabTemplate)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tabTemplate)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 684, 426))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.checkBox_CustomSpec = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_CustomSpec.setChecked(False)
        self.checkBox_CustomSpec.setObjectName("checkBox_CustomSpec")
        self.verticalLayout_4.addWidget(self.checkBox_CustomSpec)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_CustomSpec = QtWidgets.QTextEdit(self.widget)
        self.textEdit_CustomSpec.setEnabled(False)
        self.textEdit_CustomSpec.setObjectName("textEdit_CustomSpec")
        self.gridLayout.addWidget(self.textEdit_CustomSpec, 6, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.default_CustomSpec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.default_CustomSpec.setObjectName("default_CustomSpec")
        self.horizontalLayout_3.addWidget(self.default_CustomSpec)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tabTemplate, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        self.checkBox_CustomSpec.toggled['bool'].connect(self.textEdit_CustomSpec.setEnabled)
        self.checkBox_Distclean.toggled['bool'].connect(self.lineEdit_Distclean.setEnabled)
        self.checkBox_Clean.toggled['bool'].connect(self.lineEdit_Clean.setEnabled)
        self.checkBox_Build.toggled['bool'].connect(self.lineEdit_Build.setEnabled)
        self.checkBox_Deploy.toggled['bool'].connect(self.lineEdit_Deploy.setEnabled)
        self.checkBox_Run.toggled['bool'].connect(self.lineEdit_Run.setEnabled)
        self.checkBox_Serve.toggled['bool'].connect(self.lineEdit_Serve.setEnabled)
        self.checkBox_Terminal.toggled['bool'].connect(self.lineEdit_Terminal.setEnabled)
        self.checkBox_BlacklistApp.toggled['bool'].connect(self.textEdit_BlacklistApp.setEnabled)
        self.checkBox_BlacklistBuildozer.toggled['bool'].connect(self.textEdit_BlacklistBuildozer.setEnabled)
        self.checkBox_CustomSpec.toggled['bool'].connect(self.textEdit_CustomSpec.setEnabled)
        self.checkBox_SubApp.toggled['bool'].connect(self.textEdit_SubApp.setEnabled)
        self.checkBox_SubBuildozer.toggled['bool'].connect(self.textEdit_SubBuildozer.setEnabled)
        self.buttonBox.clicked['QAbstractButton*'].connect(SettingsDialog.onApply)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.checkBox_AskSaveOnClose.setText(_translate("SettingsDialog", "Ask To Save On Closing Builderton"))
        self.checkBox_RecentFiles.setText(_translate("SettingsDialog", "Recent Files History"))
        self.checkBox_SplashScreen.setText(_translate("SettingsDialog", "Show Splashscreen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingsDialog", "General"))
        self.checkBox_Distclean.setText(_translate("SettingsDialog", "Distclean"))
        self.checkBox_Terminal.setText(_translate("SettingsDialog", "Term"))
        self.lineEdit_Clean.setText(_translate("SettingsDialog", "buildozer {target} clean"))
        self.lineEdit_Deploy.setText(_translate("SettingsDialog", "buildozer {target} deploy"))
        self.checkBox_Run.setText(_translate("SettingsDialog", "Run"))
        self.lineEdit_Run.setText(_translate("SettingsDialog", "buildozer {target} run"))
        self.lineEdit_Serve.setText(_translate("SettingsDialog", "buildozer {target} serve"))
        self.checkBox_Deploy.setText(_translate("SettingsDialog", "Deploy"))
        self.checkBox_Serve.setText(_translate("SettingsDialog", "Serve"))
        self.checkBox_Build.setText(_translate("SettingsDialog", "Build"))
        self.lineEdit_Distclean.setText(_translate("SettingsDialog", "buildozer distclean"))
        self.label_10.setText(_translate("SettingsDialog", "Override terminal. This command is prepended to the buildozer commands"))
        self.lineEdit_Terminal.setText(_translate("SettingsDialog", "xterm -hold -e "))
        self.checkBox_Clean.setText(_translate("SettingsDialog", "Clean"))
        self.lineEdit_Build.setText(_translate("SettingsDialog", "buildozer {target} {buildmode}"))
        self.label_6.setText(_translate("SettingsDialog", "Override buildozer commands"))
        self.default_Clean.setText(_translate("SettingsDialog", "Default"))
        self.default_Build.setText(_translate("SettingsDialog", "Default"))
        self.default_Deploy.setText(_translate("SettingsDialog", "Default"))
        self.default_Run.setText(_translate("SettingsDialog", "Default"))
        self.default_Serve.setText(_translate("SettingsDialog", "Default"))
        self.default_Terminal.setText(_translate("SettingsDialog", "Default"))
        self.default_Distclean.setText(_translate("SettingsDialog", "Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialog", "Commands"))
        self.label_3.setText(_translate("SettingsDialog", "Add your custom own target names."))
        self.label_4.setText(_translate("SettingsDialog", "Target names are split by a newline or a comma. For example: android_small, ios_test"))
        self.label_5.setText(_translate("SettingsDialog", "This feature is intended for buildozer developers. Target names will appear in the target drop-down menu."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsDialog", "Targets"))
        self.checkBox_BlacklistApp.setText(_translate("SettingsDialog", "Use App blacklist"))
        self.checkBox_BlacklistBuildozer.setText(_translate("SettingsDialog", "Use Buildozer blacklist"))
        self.label_7.setText(_translate("SettingsDialog", "Ignore keys under the [app] section e.g. p4a.dir, p4a.branch"))
        self.label_8.setText(_translate("SettingsDialog", "Ignore keys under the [buildozer] section e.g. log_level, bin_dir"))
        self.label_9.setText(_translate("SettingsDialog", "Blacklist config keys by skipping writing them to spec file when saving"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBlacklist), _translate("SettingsDialog", "Blacklist"))
        self.checkBox_SubBuildozer.setText(_translate("SettingsDialog", "Substitute key names under [buiildozer] section"))
        self.label_12.setText(_translate("SettingsDialog", "You substitute config keys with your own. e.g. p4a.dir=p4a.dir2 will change p4a.dir to p4a.dir2"))
        self.checkBox_SubApp.setText(_translate("SettingsDialog", "Substitute key names under [app] section"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SettingsDialog", "Substitute"))
        self.label.setText(_translate("SettingsDialog", "You can define a custom spec layout"))
        self.label_2.setText(_translate("SettingsDialog", "Note: Commented lines must begin with #"))
        self.checkBox_CustomSpec.setText(_translate("SettingsDialog", "Use custom spec layout"))
        self.textEdit_CustomSpec.setHtml(_translate("SettingsDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[app]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{app}</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[buildozer]</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{buildozer}</p></body></html>"))
        self.default_CustomSpec.setText(_translate("SettingsDialog", "Restore Default Layout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTemplate), _translate("SettingsDialog", "Buildozer Spec Layout"))

